export const enum STORIES_QUERY_KEYS {
  EDIT_STORY = "EDIT_STORY",
  LIKE_STORY = "LIKE_STORY",
  SHARE_STORY = "SHARE_STORY",
  GET_STORIES = "GET_STORIES",
  DELETE_STORY = "DELETE_STORY",
  REPORT_STORY = "REPORT_STORY",
  DISLIKE_STORY = "DISLIKE_STORY",
  ADD_NEW_STORY = "ADD_NEW_STORY",
  GET_SINGLE_STORY = "GET_SINGLE_STORY",
  ADD_STORY_COMMENT = "ADD_STORY_COMMENT",
  GET_STORY_COMMENTS = "GET_STORY_COMMENTS",
}
