export const enum STORIES_QUERY_KEYS {
  GET_STORIES = "GET_STORIES",
  DELETE_STORY = "DELETE_STORY",
  ADD_NEW_STORY = "ADD_NEW_STORY",
  GET_SINGLE_STORY = "GET_SINGLE_STORY",
  ADD_STORY_COMMENT = "ADD_STORY_COMMENT",
  GET_STORY_COMMENTS = "GET_STORY_COMMENTS",
}
