export const enum USER_QUERY_KEYS {
  GET_USER_BY_ID = "GET_USER_BY_ID",
  GET_CURRENT_USER = "GET_CURRENT_USER",
  UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER",
  GET_USER_STORIES_BY_ID = "GET_USER_STORIES_BY_ID",
  GET_USER_COMMENTS_BY_ID = "GET_USER_COMMENTS_BY_ID",
  GET_USER_FOLLOWERS_LIST = "GET_USER_FOLLOWERS_LIST",
  GET_USER_FOLLOWINGS_LIST = "GET_USER_FOLLOWINGS_LIST",
  GET_CURRENT_USER_STORIES = "GET_CURRENT_USER_STORIES",
  GET_USER_PRIVATE_STORY_COUNT = "GET_USER_PRIVATE_STORY_COUNT",
}
