export const enum NOTIFICATIONS_QUERY_KEYS {
  GET_USER_NOTIFICATIONS = "GET_USER_NOTIFICATIONS",
  GET_USER_NOTIFICATIONS_UNREAD_COUNT = "GET_USER_NOTIFICATIONS_UNREAD_COUNT",
  MARK_NOTIFICATION_AS_READ = "MARK_NOTIFICATION_AS_READ",
}
