export const enum NOTIFICATIONS_QUERY_KEYS {
  GET_USER_NOTIFICATIONS = "GET_USER_NOTIFICATIONS",
  MARK_NOTIFICATION_AS_READ = "MARK_NOTIFICATION_AS_READ",
  GET_USER_UNREAD_NOTIFICATIONS_COUNT = "GET_USER_UNREAD_NOTIFICATIONS_COUNT",
}
