export const enum NOVELS_QUERY_KEYS {
  GET_NOVELS = "GET_NOVELS",
  GET_NOVEL_BY_ID = "GET_NOVEL_BY_ID",
  GET_NOVEL_LIKERS = "GET_NOVEL_LIKERS",
  GET_CHAPTER_BY_ID = "GET_CHAPTER_BY_ID",
  GET_NOVEL_COMMENTS = "GET_NOVEL_COMMENTS",
  GET_AUTHOR_OTHER_NOVELS = "GET_AUTHOR_OTHER_NOVELS",
}
